/**
 * Seed data ICD-10 Indonesia — standar INA-CBGs Kemenkes RI
 * Mencakup kode-kode yang paling umum digunakan di RS Indonesia.
 * Untuk import dataset lengkap (±14.000 kode), gunakan skrip import dari
 * file resmi Kemenkes: https://www.kemkes.go.id (INA-CBGs ICD-10 mapping)
 *
 * Format: [kode, nama_en, nama_id, bab]
 * bab format: "BAB [Romawi] — [Judul]"
 */

export const ICD10_SEED: [string, string, string, string][] = [
  // ─── BAB I — Penyakit Infeksi & Parasit ───────────────────────────────────
  ['A00',   'Cholera', 'Kolera', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A01',   'Typhoid and paratyphoid fevers', 'Demam tifoid dan paratifoid', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A01.0', 'Typhoid fever', 'Demam tifoid', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A06',   'Amoebiasis', 'Amoebiasis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A09',   'Diarrhoea and gastroenteritis', 'Diare dan gastroenteritis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A15',   'Respiratory tuberculosis', 'Tuberkulosis paru', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A16',   'Respiratory tuberculosis, not bacteriologically confirmed', 'TB paru, tidak terkonfirmasi bakteriologis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A17',   'Tuberculosis of nervous system', 'Tuberkulosis sistem saraf', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A18',   'Tuberculosis of other organs', 'Tuberkulosis organ lain', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A19',   'Miliary tuberculosis', 'Tuberkulosis milier', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A36',   'Diphtheria', 'Difteri', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A37',   'Whooping cough', 'Batuk rejan (pertusis)', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A50',   'Congenital syphilis', 'Sifilis kongenital', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A51',   'Early syphilis', 'Sifilis primer', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A54',   'Gonococcal infection', 'Infeksi gonokokal', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A63',   'Other predominantly sexually transmitted diseases', 'Penyakit menular seksual lainnya', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A77',   'Spotted fever', 'Demam tifus berbintik', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A80',   'Acute poliomyelitis', 'Poliomielitis akut', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A90',   'Dengue fever', 'Demam dengue', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A91',   'Dengue haemorrhagic fever', 'Demam berdarah dengue (DBD)', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A92',   'Other mosquito-borne viral fevers', 'Demam virus nyamuk lainnya', 'BAB I — Penyakit Infeksi & Parasit'],
  ['A95',   'Yellow fever', 'Demam kuning', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B00',   'Herpesviral infections', 'Infeksi herpes simpleks', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B01',   'Varicella (chickenpox)', 'Cacar air (varisela)', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B02',   'Zoster', 'Herpes zoster', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B05',   'Measles', 'Campak (morbili)', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B06',   'Rubella', 'Rubela', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B15',   'Acute hepatitis A', 'Hepatitis A akut', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B16',   'Acute hepatitis B', 'Hepatitis B akut', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B17',   'Other acute viral hepatitis', 'Hepatitis virus akut lainnya', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B18',   'Chronic viral hepatitis', 'Hepatitis virus kronis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B18.1', 'Chronic viral hepatitis B without delta-agent', 'Hepatitis B kronis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B18.2', 'Chronic viral hepatitis C', 'Hepatitis C kronis', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B20',   'HIV disease resulting in infectious diseases', 'HIV dengan penyakit infeksi', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B24',   'Unspecified HIV disease', 'Penyakit HIV tidak spesifik', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B34',   'Viral infection of unspecified site', 'Infeksi virus tidak spesifik', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B50',   'Plasmodium falciparum malaria', 'Malaria falsiparum', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B51',   'Plasmodium vivax malaria', 'Malaria vivaks', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B54',   'Unspecified malaria', 'Malaria tidak spesifik', 'BAB I — Penyakit Infeksi & Parasit'],
  ['B65',   'Schistosomiasis', 'Skistosomiasis', 'BAB I — Penyakit Infeksi & Parasit'],

  // ─── BAB II — Neoplasma ───────────────────────────────────────────────────
  ['C00',   'Malignant neoplasm of lip', 'Neoplasma ganas bibir', 'BAB II — Neoplasma'],
  ['C16',   'Malignant neoplasm of stomach', 'Neoplasma ganas lambung', 'BAB II — Neoplasma'],
  ['C18',   'Malignant neoplasm of colon', 'Neoplasma ganas kolon', 'BAB II — Neoplasma'],
  ['C22',   'Malignant neoplasm of liver', 'Neoplasma ganas hati', 'BAB II — Neoplasma'],
  ['C25',   'Malignant neoplasm of pancreas', 'Neoplasma ganas pankreas', 'BAB II — Neoplasma'],
  ['C34',   'Malignant neoplasm of bronchus and lung', 'Neoplasma ganas bronkus dan paru', 'BAB II — Neoplasma'],
  ['C50',   'Malignant neoplasm of breast', 'Neoplasma ganas payudara', 'BAB II — Neoplasma'],
  ['C53',   'Malignant neoplasm of cervix uteri', 'Neoplasma ganas serviks uteri', 'BAB II — Neoplasma'],
  ['C54',   'Malignant neoplasm of corpus uteri', 'Neoplasma ganas korpus uteri', 'BAB II — Neoplasma'],
  ['C56',   'Malignant neoplasm of ovary', 'Neoplasma ganas ovarium', 'BAB II — Neoplasma'],
  ['C61',   'Malignant neoplasm of prostate', 'Neoplasma ganas prostat', 'BAB II — Neoplasma'],
  ['C67',   'Malignant neoplasm of bladder', 'Neoplasma ganas kandung kemih', 'BAB II — Neoplasma'],
  ['C73',   'Malignant neoplasm of thyroid gland', 'Neoplasma ganas kelenjar tiroid', 'BAB II — Neoplasma'],
  ['C80',   'Malignant neoplasm without specification of site', 'Neoplasma ganas tanpa lokasi spesifik', 'BAB II — Neoplasma'],
  ['C91',   'Lymphoid leukaemia', 'Leukemia limfoid', 'BAB II — Neoplasma'],
  ['C92',   'Myeloid leukaemia', 'Leukemia mieloid', 'BAB II — Neoplasma'],
  ['D05',   'Carcinoma in situ of breast', 'Karsinoma in situ payudara', 'BAB II — Neoplasma'],
  ['D25',   'Leiomyoma of uterus', 'Leiomioma uteri (mioma)', 'BAB II — Neoplasma'],
  ['D35',   'Benign neoplasm of other endocrine glands', 'Neoplasma jinak kelenjar endokrin lain', 'BAB II — Neoplasma'],

  // ─── BAB III — Darah & Organ Pembentuk Darah ──────────────────────────────
  ['D50',   'Iron deficiency anaemia', 'Anemia defisiensi besi', 'BAB III — Darah & Organ Pembentuk Darah'],
  ['D51',   'Vitamin B12 deficiency anaemia', 'Anemia defisiensi vitamin B12', 'BAB III — Darah & Organ Pembentuk Darah'],
  ['D55',   'Anaemia due to enzyme disorders', 'Anemia akibat gangguan enzim', 'BAB III — Darah & Organ Pembentuk Darah'],
  ['D57',   'Sickle-cell disorders', 'Anemia sel sabit', 'BAB III — Darah & Organ Pembentuk Darah'],
  ['D64',   'Other anaemias', 'Anemia lainnya', 'BAB III — Darah & Organ Pembentuk Darah'],
  ['D69',   'Purpura and other haemorrhagic conditions', 'Purpura dan kondisi hemoragik lain', 'BAB III — Darah & Organ Pembentuk Darah'],

  // ─── BAB IV — Endokrin, Nutrisi & Metabolisme ────────────────────────────
  ['E03',   'Other hypothyroidism', 'Hipotiroidisme lainnya', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E04',   'Other non-toxic goitre', 'Gondok non-toksik lainnya', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E05',   'Thyrotoxicosis', 'Tirotoksikosis (hipertiroid)', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E06',   'Thyroiditis', 'Tiroiditis', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E10',   'Type 1 diabetes mellitus', 'Diabetes melitus tipe 1', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E10.0', 'Type 1 diabetes mellitus with coma', 'DM tipe 1 dengan koma', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E10.5', 'Type 1 diabetes mellitus with peripheral circulatory complications', 'DM tipe 1 dengan komplikasi sirkulasi perifer', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E10.6', 'Type 1 diabetes mellitus with other specified complications', 'DM tipe 1 dengan komplikasi lain', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11',   'Type 2 diabetes mellitus', 'Diabetes melitus tipe 2', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.0', 'Type 2 diabetes mellitus with coma', 'DM tipe 2 dengan koma', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.1', 'Type 2 diabetes mellitus with ketoacidosis', 'DM tipe 2 dengan ketoasidosis', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.2', 'Type 2 diabetes mellitus with renal complications', 'DM tipe 2 dengan komplikasi ginjal', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.3', 'Type 2 diabetes mellitus with ophthalmic complications', 'DM tipe 2 dengan komplikasi mata', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.4', 'Type 2 diabetes mellitus with neurological complications', 'DM tipe 2 dengan komplikasi neurologis', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.5', 'Type 2 diabetes mellitus with peripheral circulatory complications', 'DM tipe 2 dengan komplikasi sirkulasi perifer', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.6', 'Type 2 diabetes mellitus with other specified complications', 'DM tipe 2 dengan komplikasi lain', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.7', 'Type 2 diabetes mellitus with multiple complications', 'DM tipe 2 dengan komplikasi multipel', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.9', 'Type 2 diabetes mellitus without complications', 'DM tipe 2 tanpa komplikasi', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E13',   'Other specified diabetes mellitus', 'Diabetes melitus jenis lain', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E14',   'Unspecified diabetes mellitus', 'Diabetes melitus tidak spesifik', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E11.65','Type 2 DM with hyperglycaemia', 'DM tipe 2 dengan hiperglikemia', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E27',   'Other disorders of adrenal gland', 'Gangguan kelenjar adrenal lainnya', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E40',   'Kwashiorkor', 'Kwasiorkhor', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E43',   'Unspecified severe protein-energy malnutrition', 'Malnutrisi protein-energi berat tidak spesifik', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E44',   'Protein-energy malnutrition of moderate and mild degree', 'Malnutrisi protein-energi derajat sedang dan ringan', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E46',   'Unspecified protein-energy malnutrition', 'Malnutrisi protein-energi tidak spesifik', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E50',   'Vitamin A deficiency', 'Defisiensi vitamin A', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E55',   'Vitamin D deficiency', 'Defisiensi vitamin D', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E66',   'Obesity', 'Obesitas', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E78',   'Disorders of lipoprotein metabolism', 'Gangguan metabolisme lipoprotein (dislipidemia)', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E78.0', 'Pure hypercholesterolaemia', 'Hiperkolesterolemia murni', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E78.1', 'Pure hypertriglyceridaemia', 'Hipertrigliseridemia murni', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E78.5', 'Hyperlipidaemia, unspecified', 'Hiperlipidemia tidak spesifik', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E79',   'Disorders of purine and pyrimidine metabolism', 'Gangguan metabolisme purin (asam urat)', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E83',   'Disorders of mineral metabolism', 'Gangguan metabolisme mineral', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],
  ['E87',   'Other disorders of fluid, electrolyte and acid-base balance', 'Gangguan cairan, elektrolit, dan keseimbangan asam basa', 'BAB IV — Endokrin, Nutrisi & Metabolisme'],

  // ─── BAB V — Gangguan Mental & Perilaku ──────────────────────────────────
  ['F00',   'Dementia in Alzheimer disease', 'Demensia pada penyakit Alzheimer', 'BAB V — Gangguan Mental & Perilaku'],
  ['F03',   'Unspecified dementia', 'Demensia tidak spesifik', 'BAB V — Gangguan Mental & Perilaku'],
  ['F10',   'Mental and behavioural disorders due to alcohol', 'Gangguan mental akibat alkohol', 'BAB V — Gangguan Mental & Perilaku'],
  ['F20',   'Schizophrenia', 'Skizofrenia', 'BAB V — Gangguan Mental & Perilaku'],
  ['F25',   'Schizoaffective disorders', 'Gangguan skizoafektif', 'BAB V — Gangguan Mental & Perilaku'],
  ['F31',   'Bipolar affective disorder', 'Gangguan afektif bipolar', 'BAB V — Gangguan Mental & Perilaku'],
  ['F32',   'Depressive episode', 'Episode depresif', 'BAB V — Gangguan Mental & Perilaku'],
  ['F33',   'Recurrent depressive disorder', 'Gangguan depresif berulang', 'BAB V — Gangguan Mental & Perilaku'],
  ['F40',   'Phobic anxiety disorders', 'Gangguan fobia', 'BAB V — Gangguan Mental & Perilaku'],
  ['F41',   'Other anxiety disorders', 'Gangguan ansietas lainnya', 'BAB V — Gangguan Mental & Perilaku'],
  ['F43',   'Reaction to severe stress and adjustment disorders', 'Reaksi stres berat dan gangguan penyesuaian', 'BAB V — Gangguan Mental & Perilaku'],

  // ─── BAB VI — Sistem Saraf ────────────────────────────────────────────────
  ['G20',   'Parkinson disease', 'Penyakit Parkinson', 'BAB VI — Sistem Saraf'],
  ['G30',   'Alzheimer disease', 'Penyakit Alzheimer', 'BAB VI — Sistem Saraf'],
  ['G40',   'Epilepsy', 'Epilepsi', 'BAB VI — Sistem Saraf'],
  ['G43',   'Migraine', 'Migrain', 'BAB VI — Sistem Saraf'],
  ['G45',   'Transient cerebral ischaemic attacks', 'Serangan iskemik serebral transien (TIA)', 'BAB VI — Sistem Saraf'],
  ['G47',   'Sleep disorders', 'Gangguan tidur', 'BAB VI — Sistem Saraf'],
  ['G61',   'Inflammatory polyneuropathy', 'Polineuropati inflamasi', 'BAB VI — Sistem Saraf'],
  ['G62',   'Other polyneuropathies', 'Polineuropati lainnya', 'BAB VI — Sistem Saraf'],
  ['G63',   'Polyneuropathy in diseases classified elsewhere', 'Polineuropati pada penyakit lain', 'BAB VI — Sistem Saraf'],

  // ─── BAB VII — Mata & Adneksa ─────────────────────────────────────────────
  ['H25',   'Senile cataract', 'Katarak senilis', 'BAB VII — Mata & Adneksa'],
  ['H26',   'Other cataract', 'Katarak lainnya', 'BAB VII — Mata & Adneksa'],
  ['H33',   'Retinal detachments and breaks', 'Ablasio retina', 'BAB VII — Mata & Adneksa'],
  ['H35',   'Other retinal disorders', 'Gangguan retina lainnya', 'BAB VII — Mata & Adneksa'],
  ['H36',   'Retinal disorders in diseases classified elsewhere', 'Gangguan retina pada penyakit lain (retinopati diabetik)', 'BAB VII — Mata & Adneksa'],
  ['H40',   'Glaucoma', 'Glaukoma', 'BAB VII — Mata & Adneksa'],
  ['H52',   'Disorders of refraction and accommodation', 'Kelainan refraksi (miopi, hipermetropi, astigmat)', 'BAB VII — Mata & Adneksa'],

  // ─── BAB VIII — Telinga & Mastoid ─────────────────────────────────────────
  ['H65',   'Nonsuppurative otitis media', 'Otitis media non-supuratif', 'BAB VIII — Telinga & Mastoid'],
  ['H66',   'Suppurative and unspecified otitis media', 'Otitis media supuratif (OMSK)', 'BAB VIII — Telinga & Mastoid'],
  ['H90',   'Conductive and sensorineural hearing loss', 'Gangguan pendengaran konduktif dan sensorineural', 'BAB VIII — Telinga & Mastoid'],
  ['H91',   'Other hearing loss', 'Gangguan pendengaran lainnya', 'BAB VIII — Telinga & Mastoid'],

  // ─── BAB IX — Sistem Sirkulasi ────────────────────────────────────────────
  ['I05',   'Rheumatic mitral valve diseases', 'Penyakit katup mitral reumatik', 'BAB IX — Sistem Sirkulasi'],
  ['I10',   'Essential (primary) hypertension', 'Hipertensi esensial (primer)', 'BAB IX — Sistem Sirkulasi'],
  ['I11',   'Hypertensive heart disease', 'Penyakit jantung hipertensif', 'BAB IX — Sistem Sirkulasi'],
  ['I12',   'Hypertensive renal disease', 'Penyakit ginjal hipertensif', 'BAB IX — Sistem Sirkulasi'],
  ['I13',   'Hypertensive heart and renal disease', 'Penyakit jantung dan ginjal hipertensif', 'BAB IX — Sistem Sirkulasi'],
  ['I20',   'Angina pectoris', 'Angina pektoris', 'BAB IX — Sistem Sirkulasi'],
  ['I21',   'Acute myocardial infarction', 'Infark miokard akut (serangan jantung)', 'BAB IX — Sistem Sirkulasi'],
  ['I21.0', 'Acute transmural myocardial infarction of anterior wall', 'Infark miokard akut dinding anterior', 'BAB IX — Sistem Sirkulasi'],
  ['I21.1', 'Acute transmural myocardial infarction of inferior wall', 'Infark miokard akut dinding inferior', 'BAB IX — Sistem Sirkulasi'],
  ['I22',   'Subsequent myocardial infarction', 'Infark miokard berikutnya', 'BAB IX — Sistem Sirkulasi'],
  ['I25',   'Chronic ischaemic heart disease', 'Penyakit jantung iskemik kronis', 'BAB IX — Sistem Sirkulasi'],
  ['I26',   'Pulmonary embolism', 'Emboli paru', 'BAB IX — Sistem Sirkulasi'],
  ['I34',   'Nonrheumatic mitral valve disorders', 'Gangguan katup mitral non-reumatik', 'BAB IX — Sistem Sirkulasi'],
  ['I42',   'Cardiomyopathy', 'Kardiomiopati', 'BAB IX — Sistem Sirkulasi'],
  ['I48',   'Atrial fibrillation and flutter', 'Fibrilasi dan flutter atrium', 'BAB IX — Sistem Sirkulasi'],
  ['I50',   'Heart failure', 'Gagal jantung', 'BAB IX — Sistem Sirkulasi'],
  ['I50.0', 'Congestive heart failure', 'Gagal jantung kongestif', 'BAB IX — Sistem Sirkulasi'],
  ['I63',   'Cerebral infarction', 'Infark serebral (stroke iskemik)', 'BAB IX — Sistem Sirkulasi'],
  ['I64',   'Stroke, not specified as haemorrhage or infarction', 'Stroke tidak spesifik', 'BAB IX — Sistem Sirkulasi'],
  ['I65',   'Occlusion and stenosis of precerebral arteries', 'Oklusi dan stenosis arteri praserebral', 'BAB IX — Sistem Sirkulasi'],
  ['I67',   'Other cerebrovascular diseases', 'Penyakit serebrovaskular lainnya', 'BAB IX — Sistem Sirkulasi'],
  ['I69',   'Sequelae of cerebrovascular disease', 'Sekuele penyakit serebrovaskular (pasca stroke)', 'BAB IX — Sistem Sirkulasi'],
  ['I70',   'Atherosclerosis', 'Aterosklerosis', 'BAB IX — Sistem Sirkulasi'],
  ['I73',   'Other peripheral vascular diseases', 'Penyakit vaskular perifer lainnya', 'BAB IX — Sistem Sirkulasi'],
  ['I83',   'Varicose veins of lower extremities', 'Varises ekstremitas bawah', 'BAB IX — Sistem Sirkulasi'],

  // ─── BAB X — Sistem Pernapasan ────────────────────────────────────────────
  ['J00',   'Acute nasopharyngitis (common cold)', 'Nasofaringitis akut (flu biasa)', 'BAB X — Sistem Pernapasan'],
  ['J02',   'Acute pharyngitis', 'Faringitis akut', 'BAB X — Sistem Pernapasan'],
  ['J03',   'Acute tonsillitis', 'Tonsilitis akut', 'BAB X — Sistem Pernapasan'],
  ['J04',   'Acute laryngitis and tracheitis', 'Laringitis dan trakeitis akut', 'BAB X — Sistem Pernapasan'],
  ['J06',   'Acute upper respiratory infections, multiple and unspecified sites', 'ISPA (infeksi saluran napas atas akut)', 'BAB X — Sistem Pernapasan'],
  ['J11',   'Influenza, virus not identified', 'Influenza, virus tidak teridentifikasi', 'BAB X — Sistem Pernapasan'],
  ['J12',   'Viral pneumonia', 'Pneumonia virus', 'BAB X — Sistem Pernapasan'],
  ['J13',   'Pneumonia due to Streptococcus pneumoniae', 'Pneumonia akibat Streptococcus pneumoniae', 'BAB X — Sistem Pernapasan'],
  ['J15',   'Unspecified bacterial pneumonia', 'Pneumonia bakterial tidak spesifik', 'BAB X — Sistem Pernapasan'],
  ['J18',   'Pneumonia, unspecified organism', 'Pneumonia tidak spesifik', 'BAB X — Sistem Pernapasan'],
  ['J20',   'Acute bronchitis', 'Bronkitis akut', 'BAB X — Sistem Pernapasan'],
  ['J22',   'Unspecified acute lower respiratory infection', 'Infeksi saluran napas bawah akut tidak spesifik', 'BAB X — Sistem Pernapasan'],
  ['J30',   'Vasomotor and allergic rhinitis', 'Rinitis vasomotor dan alergik', 'BAB X — Sistem Pernapasan'],
  ['J35',   'Chronic diseases of tonsils and adenoids', 'Penyakit kronis tonsil dan adenoid', 'BAB X — Sistem Pernapasan'],
  ['J40',   'Bronchitis, not specified as acute or chronic', 'Bronkitis tidak spesifik', 'BAB X — Sistem Pernapasan'],
  ['J41',   'Simple and mucopurulent chronic bronchitis', 'Bronkitis kronis simpleks dan mukopurulen', 'BAB X — Sistem Pernapasan'],
  ['J44',   'Other chronic obstructive pulmonary disease (COPD)', 'Penyakit paru obstruktif kronis (PPOK)', 'BAB X — Sistem Pernapasan'],
  ['J45',   'Asthma', 'Asma', 'BAB X — Sistem Pernapasan'],
  ['J45.0', 'Predominantly allergic asthma', 'Asma alergi predominan', 'BAB X — Sistem Pernapasan'],
  ['J45.1', 'Nonallergic asthma', 'Asma non-alergi', 'BAB X — Sistem Pernapasan'],
  ['J46',   'Status asthmaticus', 'Status asmatikus', 'BAB X — Sistem Pernapasan'],
  ['J47',   'Bronchiectasis', 'Bronkiektasis', 'BAB X — Sistem Pernapasan'],
  ['J81',   'Pulmonary oedema', 'Edema paru', 'BAB X — Sistem Pernapasan'],
  ['J90',   'Pleural effusion', 'Efusi pleura', 'BAB X — Sistem Pernapasan'],
  ['J96',   'Respiratory failure', 'Gagal napas', 'BAB X — Sistem Pernapasan'],

  // ─── BAB XI — Sistem Pencernaan ───────────────────────────────────────────
  ['K02',   'Dental caries', 'Karies gigi', 'BAB XI — Sistem Pencernaan'],
  ['K04',   'Diseases of pulp and periapical tissues', 'Penyakit pulpa dan jaringan periapikal', 'BAB XI — Sistem Pencernaan'],
  ['K21',   'Gastro-oesophageal reflux disease (GERD)', 'Penyakit refluks gastroesofageal (GERD)', 'BAB XI — Sistem Pencernaan'],
  ['K25',   'Gastric ulcer', 'Ulkus lambung (tukak lambung)', 'BAB XI — Sistem Pencernaan'],
  ['K26',   'Duodenal ulcer', 'Ulkus duodenum', 'BAB XI — Sistem Pencernaan'],
  ['K27',   'Peptic ulcer', 'Ulkus peptikum', 'BAB XI — Sistem Pencernaan'],
  ['K29',   'Gastritis and duodenitis', 'Gastritis dan duodenitis', 'BAB XI — Sistem Pencernaan'],
  ['K29.7', 'Gastritis, unspecified', 'Gastritis tidak spesifik', 'BAB XI — Sistem Pencernaan'],
  ['K30',   'Dyspepsia', 'Dispepsia', 'BAB XI — Sistem Pencernaan'],
  ['K35',   'Acute appendicitis', 'Apendisitis akut', 'BAB XI — Sistem Pencernaan'],
  ['K37',   'Unspecified appendicitis', 'Apendisitis tidak spesifik', 'BAB XI — Sistem Pencernaan'],
  ['K40',   'Inguinal hernia', 'Hernia inguinalis', 'BAB XI — Sistem Pencernaan'],
  ['K41',   'Femoral hernia', 'Hernia femoralis', 'BAB XI — Sistem Pencernaan'],
  ['K42',   'Umbilical hernia', 'Hernia umbilikalis', 'BAB XI — Sistem Pencernaan'],
  ['K50',   "Crohn disease", 'Penyakit Crohn', 'BAB XI — Sistem Pencernaan'],
  ['K51',   'Ulcerative colitis', 'Kolitis ulseratif', 'BAB XI — Sistem Pencernaan'],
  ['K57',   'Diverticular disease of intestine', 'Penyakit divertikular usus', 'BAB XI — Sistem Pencernaan'],
  ['K70',   'Alcoholic liver disease', 'Penyakit hati alkoholik', 'BAB XI — Sistem Pencernaan'],
  ['K72',   'Hepatic failure', 'Gagal hati', 'BAB XI — Sistem Pencernaan'],
  ['K74',   'Fibrosis and cirrhosis of liver', 'Fibrosis dan sirosis hati', 'BAB XI — Sistem Pencernaan'],
  ['K75',   'Other inflammatory liver diseases', 'Penyakit hati inflamasi lainnya', 'BAB XI — Sistem Pencernaan'],
  ['K76',   'Other diseases of liver', 'Penyakit hati lainnya', 'BAB XI — Sistem Pencernaan'],
  ['K80',   'Cholelithiasis (gallstones)', 'Kolelitiasis (batu empedu)', 'BAB XI — Sistem Pencernaan'],
  ['K81',   'Cholecystitis', 'Kolesistitis', 'BAB XI — Sistem Pencernaan'],
  ['K85',   'Acute pancreatitis', 'Pankreatitis akut', 'BAB XI — Sistem Pencernaan'],
  ['K86',   'Other diseases of pancreas', 'Penyakit pankreas lainnya', 'BAB XI — Sistem Pencernaan'],
  ['K92',   'Other diseases of digestive system', 'Penyakit sistem pencernaan lainnya', 'BAB XI — Sistem Pencernaan'],

  // ─── BAB XII — Kulit & Jaringan Subkutan ──────────────────────────────────
  ['L02',   'Cutaneous abscess, furuncle and carbuncle', 'Abses kulit, furunkel, dan karbunkel', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L03',   'Cellulitis', 'Selulitis', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L20',   'Atopic dermatitis', 'Dermatitis atopik', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L23',   'Allergic contact dermatitis', 'Dermatitis kontak alergik', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L30',   'Other dermatitis', 'Dermatitis lainnya', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L40',   'Psoriasis', 'Psoriasis', 'BAB XII — Kulit & Jaringan Subkutan'],
  ['L50',   'Urticaria', 'Urtikaria (biduran)', 'BAB XII — Kulit & Jaringan Subkutan'],

  // ─── BAB XIII — Muskuloskeletal & Jaringan Ikat ───────────────────────────
  ['M05',   'Seropositive rheumatoid arthritis', 'Artritis reumatoid seropositif', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M06',   'Other rheumatoid arthritis', 'Artritis reumatoid lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M10',   'Gout', 'Gout (asam urat)', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M17',   'Gonarthrosis (arthrosis of knee)', 'Gonarthrosis (OA lutut)', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M19',   'Other arthrosis', 'Artrosis lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M25',   'Other joint disorders', 'Gangguan sendi lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M32',   'Systemic lupus erythematosus (SLE)', 'Lupus eritematosus sistemik (LES)', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M41',   'Scoliosis', 'Skoliosis', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M47',   'Spondylosis', 'Spondilosis', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M48',   'Other spondylopathies', 'Spondylopati lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M50',   'Cervical disc disorders', 'Gangguan diskus servikal', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M51',   'Other intervertebral disc degeneration', 'Degenerasi diskus intervertebral lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M54',   'Dorsalgia', 'Nyeri punggung (dorsalgia)', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M54.5', 'Low back pain', 'Nyeri punggung bawah (LBP)', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M79',   'Other soft tissue disorders', 'Gangguan jaringan lunak lainnya', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M80',   'Osteoporosis with pathological fracture', 'Osteoporosis dengan fraktur patologis', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],
  ['M81',   'Osteoporosis without pathological fracture', 'Osteoporosis tanpa fraktur patologis', 'BAB XIII — Muskuloskeletal & Jaringan Ikat'],

  // ─── BAB XIV — Sistem Genitourinaria ──────────────────────────────────────
  ['N00',   'Acute nephritic syndrome', 'Sindrom nefritis akut', 'BAB XIV — Sistem Genitourinaria'],
  ['N03',   'Chronic nephritic syndrome', 'Sindrom nefritis kronis', 'BAB XIV — Sistem Genitourinaria'],
  ['N04',   'Nephrotic syndrome', 'Sindrom nefrotik', 'BAB XIV — Sistem Genitourinaria'],
  ['N18',   'Chronic kidney disease (CKD)', 'Penyakit ginjal kronis (PGK)', 'BAB XIV — Sistem Genitourinaria'],
  ['N18.1', 'Chronic kidney disease, stage 1', 'PGK stadium 1', 'BAB XIV — Sistem Genitourinaria'],
  ['N18.2', 'Chronic kidney disease, stage 2', 'PGK stadium 2', 'BAB XIV — Sistem Genitourinaria'],
  ['N18.3', 'Chronic kidney disease, stage 3', 'PGK stadium 3', 'BAB XIV — Sistem Genitourinaria'],
  ['N18.4', 'Chronic kidney disease, stage 4', 'PGK stadium 4', 'BAB XIV — Sistem Genitourinaria'],
  ['N18.5', 'Chronic kidney disease, stage 5', 'PGK stadium 5 (gagal ginjal)', 'BAB XIV — Sistem Genitourinaria'],
  ['N19',   'Unspecified kidney failure', 'Gagal ginjal tidak spesifik', 'BAB XIV — Sistem Genitourinaria'],
  ['N20',   'Calculus of kidney and ureter', 'Batu ginjal dan ureter (nefrolitiasis)', 'BAB XIV — Sistem Genitourinaria'],
  ['N21',   'Calculus of lower urinary tract', 'Batu saluran kemih bawah', 'BAB XIV — Sistem Genitourinaria'],
  ['N30',   'Cystitis', 'Sistitis', 'BAB XIV — Sistem Genitourinaria'],
  ['N39',   'Other disorders of urinary system', 'Gangguan sistem kemih lainnya (ISK)', 'BAB XIV — Sistem Genitourinaria'],
  ['N39.0', 'Urinary tract infection, site not specified', 'Infeksi saluran kemih (ISK)', 'BAB XIV — Sistem Genitourinaria'],
  ['N40',   'Benign prostatic hyperplasia (BPH)', 'Hiperplasia prostat jinak (BPH)', 'BAB XIV — Sistem Genitourinaria'],
  ['N60',   'Benign mammary dysplasias', 'Displasia mamae jinak', 'BAB XIV — Sistem Genitourinaria'],
  ['N63',   'Unspecified lump in breast', 'Benjolan payudara tidak spesifik', 'BAB XIV — Sistem Genitourinaria'],
  ['N80',   'Endometriosis', 'Endometriosis', 'BAB XIV — Sistem Genitourinaria'],
  ['N83',   'Non-inflammatory disorders of ovary, fallopian tube and broad ligament', 'Gangguan non-inflamasi ovarium (kista ovarium)', 'BAB XIV — Sistem Genitourinaria'],
  ['N92',   'Excessive, frequent and irregular menstruation', 'Menstruasi berlebihan dan tidak teratur', 'BAB XIV — Sistem Genitourinaria'],
  ['N93',   'Other abnormal uterine and vaginal bleeding', 'Perdarahan uterus dan vagina abnormal lainnya', 'BAB XIV — Sistem Genitourinaria'],

  // ─── BAB XV — Kehamilan, Persalinan & Nifas ───────────────────────────────
  ['O03',   'Spontaneous abortion', 'Abortus spontan', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O10',   'Pre-existing hypertension complicating pregnancy', 'Hipertensi yang sudah ada, komplikasi kehamilan', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O13',   'Gestational hypertension', 'Hipertensi gestasional', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O14',   'Pre-eclampsia', 'Pre-eklamsia', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O14.1', 'Severe pre-eclampsia', 'Pre-eklamsia berat (PEB)', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O15',   'Eclampsia', 'Eklamsia', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O20',   'Haemorrhage in early pregnancy', 'Perdarahan awal kehamilan', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O24',   'Diabetes mellitus in pregnancy', 'Diabetes melitus gestasional', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O34',   'Maternal care for known or suspected abnormality of pelvic organs', 'Perawatan maternal — kelainan organ panggul', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O42',   'Premature rupture of membranes', 'Ketuban pecah dini (KPD)', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O60',   'Preterm labour', 'Persalinan preterm', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O80',   'Single spontaneous delivery', 'Persalinan normal spontan', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O82',   'Single delivery by caesarean section', 'Persalinan dengan seksio sesarea', 'BAB XV — Kehamilan, Persalinan & Nifas'],
  ['O85',   'Puerperal sepsis', 'Sepsis puerperalis', 'BAB XV — Kehamilan, Persalinan & Nifas'],

  // ─── BAB XVI — Kondisi Perinatal ──────────────────────────────────────────
  ['P07',   'Disorders related to short gestation and low birth weight', 'Bayi prematur dan berat badan lahir rendah (BBLR)', 'BAB XVI — Kondisi Perinatal'],
  ['P22',   'Respiratory distress of newborn', 'Gawat napas neonatus', 'BAB XVI — Kondisi Perinatal'],
  ['P36',   'Bacterial sepsis of newborn', 'Sepsis bakterial neonatus', 'BAB XVI — Kondisi Perinatal'],
  ['P55',   'Haemolytic disease of newborn', 'Penyakit hemolitik neonatus', 'BAB XVI — Kondisi Perinatal'],
  ['P59',   'Neonatal jaundice', 'Ikterus neonatorum', 'BAB XVI — Kondisi Perinatal'],

  // ─── BAB XIX — Cedera, Keracunan & Akibat Penyebab Luar ──────────────────
  ['S00',   'Superficial injury of head', 'Cedera superfisial kepala', 'BAB XIX — Cedera & Keracunan'],
  ['S06',   'Intracranial injury', 'Cedera intrakranial', 'BAB XIX — Cedera & Keracunan'],
  ['S06.0', 'Concussion', 'Konkusi (gegar otak)', 'BAB XIX — Cedera & Keracunan'],
  ['S06.2', 'Diffuse brain injury', 'Cedera otak difus', 'BAB XIX — Cedera & Keracunan'],
  ['S09',   'Other and unspecified injuries of head', 'Cedera kepala lainnya', 'BAB XIX — Cedera & Keracunan'],
  ['S52',   'Fracture of forearm', 'Fraktur lengan bawah', 'BAB XIX — Cedera & Keracunan'],
  ['S72',   'Fracture of femur', 'Fraktur femur', 'BAB XIX — Cedera & Keracunan'],
  ['S82',   'Fracture of lower leg, including ankle', 'Fraktur tungkai bawah termasuk pergelangan kaki', 'BAB XIX — Cedera & Keracunan'],
  ['T14',   'Injury of unspecified body region', 'Cedera bagian tubuh tidak spesifik', 'BAB XIX — Cedera & Keracunan'],
  ['T36',   'Poisoning by systemic antibiotics', 'Keracunan antibiotik sistemik', 'BAB XIX — Cedera & Keracunan'],
  ['T39',   'Poisoning by nonopioid analgesics', 'Keracunan analgesik non-opioid', 'BAB XIX — Cedera & Keracunan'],
  ['T78',   'Adverse effects, not elsewhere classified', 'Efek samping tidak terklasifikasi (alergi obat)', 'BAB XIX — Cedera & Keracunan'],
  ['T78.1', 'Other adverse food reactions', 'Reaksi makanan merugikan lainnya', 'BAB XIX — Cedera & Keracunan'],
  ['T78.4', 'Allergy, unspecified', 'Alergi tidak spesifik', 'BAB XIX — Cedera & Keracunan'],

  // ─── BAB XXI — Faktor yang Mempengaruhi Status Kesehatan (Z) ─────────────
  ['Z00',   'General examination and investigation of persons without complaint', 'Pemeriksaan umum orang sehat (medical check-up)', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z03',   'Medical observation for suspected diseases and conditions', 'Observasi medis untuk kondisi yang dicurigai', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z12',   'Special screening examination for neoplasms', 'Skrining neoplasma', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z13',   'Special screening examination for other diseases', 'Skrining penyakit lainnya', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z23',   'Encounter for immunization', 'Imunisasi', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z34',   'Encounter for supervision of normal pregnancy', 'Pengawasan kehamilan normal (ANC)', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z39',   'Encounter for postpartum care and examination', 'Perawatan pasca persalinan', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z51',   'Encounter for other aftercare and medical care', 'Perawatan medis lanjutan', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z51.1', 'Encounter for antineoplastic chemotherapy', 'Kemoterapi', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z54',   'Convalescence', 'Masa pemulihan (konvalesens)', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z76',   'Persons encountering health services in other circumstances', 'Kontak layanan kesehatan kondisi lainnya', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z82',   'Family history of certain disabilities and chronic diseases', 'Riwayat keluarga penyakit kronis', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z87',   'Personal history of other diseases and conditions', 'Riwayat pribadi penyakit lainnya', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
  ['Z96',   'Presence of other functional implants', 'Adanya implan fungsional', 'BAB XXI — Status Kesehatan & Kontak Layanan'],
]

/**
 * Placeholder untuk ICD-11 — akan diisi setelah WHO merilis terjemahan resmi Indonesia.
 * ICD-11 mulai berlaku di Indonesia secara bertahap; INA-CBGs masih menggunakan ICD-10.
 */
export const ICD11_SEED: [string, string, string, string][] = [
  // Struktur sama: [kode, nama_en, nama_id, bab]
  // Contoh kode ICD-11 (format baru: alfanumerik lebih panjang)
  ['5A10',  'Type 1 diabetes mellitus', 'Diabetes melitus tipe 1', 'BAB 05 — Endokrin, Nutrisi & Metabolisme'],
  ['5A11',  'Type 2 diabetes mellitus', 'Diabetes melitus tipe 2', 'BAB 05 — Endokrin, Nutrisi & Metabolisme'],
  ['BA00',  'Essential hypertension', 'Hipertensi esensial', 'BAB 11 — Sistem Sirkulasi'],
  ['BA80',  'Heart failure', 'Gagal jantung', 'BAB 11 — Sistem Sirkulasi'],
  ['8B20',  'Cerebral ischaemic stroke', 'Stroke iskemik', 'BAB 08 — Sistem Saraf'],
  ['CA22',  'Asthma', 'Asma', 'BAB 12 — Sistem Pernapasan'],
  ['GB60',  'Chronic kidney disease', 'Penyakit ginjal kronis', 'BAB 16 — Sistem Genitourinaria'],
]
